.TH LC_CTX_FREE 3 2020-08-01 "LIBRECAST" "Librecast Programmer's Manual"
.SH NAME
lc_ctx_free \- free Librecast context
.SH SYNOPSIS
.nf
.B #include <librecast/net.h>
.PP
.BI "void lc_ctx_free(lc_ctx_t " "*ctx" );
.PP
Compile and link with \fI\-llibrecast\fP.
.SH DESCRIPTION
Invalidate and free Librecast context created with 
.BR lc_ctx_new (3)
and clean up environment.
.SH RETURN VALUE
The
.BR lc_ctx_free ()
function returns no value.
.SH EXAMPLE
.SS Program source
\&
.EX
lc_ctx_t *lctx;
lctx = lc_ctx_free();

/* your Librecast program here */

lc_ctx_free(lctx); /* free context when done */
.EE
.SH SEE ALSO
.BR lc_ctx_new (3)
