.TH LC_CHANNEL_GETVAL 3 2020-08-01 "LIBRECAST" "Librecast Programmer's Manual"
.SH NAME
lc_channel_getval, lc_channel_setval \- get/set Librecast channel key/values
.SH SYNOPSIS
.nf
.B #include <librecast/netdb.h>
.PP
.BI "int lc_channel_getval(lc_channel_t " "*chan", " " lc_val_t " *key");
.BI "int lc_channel_setval(lc_channel_t " "*chan", " " lc_val_t " *key", " " lc_val_t " *val");
.fi
.PP
Compile and link with \fI\-llibrecast\fP.
.SH DESCRIPTION
.BR lc_channel_getval ()
sends a request to retrieve a Librecast Channel value.
.PP
.BR lc_channel_setval ()
Sends a request to set a Librecast Channel key/value pair.
.
.SH RETURN VALUE
Both functions return 0 on success, non-zero on failure. If the return code is
-1, check errno for the error code.  Positive return codes are
Librecast-specific.
.SH ERRORS
The following error codes may be returned:
.PP
.B LC_ERROR_NET_SEND (16)
Error sending data.
.PP
.B LC_ERROR_CHANNEL_REQUIRED (50)
.BI "" chan
argument was NULL.
.PP
.B LC_ERROR_INVALID_PARAMS (53)
Invalid arguments to function.
.PP
If -1 is returned, check errno for the follwing error:
.B ENOMEM
Out of memory.
Possibly, the application hit the
.BR RLIMIT_AS
or
.BR RLIMIT_DATA
limit described in
.BR getrlimit (2).
.SH SEE ALSO
.BR lc_ctx_free (3)
